"""Tests for systems/code_gen.py — file write + path safety."""
from __future__ import annotations

import os

import pytest


def test_safe_path_component_strips_traversal():
    from systems.code_gen import _safe_path_component

    # basename+sanitise should never leave `..` in the result
    for bad in ("../../etc/passwd", "..\\..\\secret", "../../../escape.py"):
        out = _safe_path_component(bad, "x.txt")
        assert ".." not in out
        assert "/" not in out and "\\" not in out
    assert _safe_path_component("", "fallback.py") == "fallback.py"


def test_safe_path_component_drops_hidden_prefix():
    from systems.code_gen import _safe_path_component

    out = _safe_path_component(".hidden", "x")
    assert not out.startswith(".")


def test_save_code_refuses_outside_output_dir(tmp_path, monkeypatch):
    """Guard must refuse to write outside CODE_OUTPUT_DIR."""
    import systems.code_gen as cg
    from core.enums import CodeLanguage, EntityType, Gender, Role
    from core.models import CodeSnippet, Entity

    monkeypatch.setattr(cg, "CODE_OUTPUT_DIR", str(tmp_path / "output"))

    # Minimal world stub — only .settlements needed.
    class StubWorld:
        settlements: dict = {}

    entity = Entity(
        id=1, x=0.0, y=0.0, entity_type=EntityType.DEVELOPER,
        energy=0.8, gender=Gender.FRONTEND_SPEC, role=Role.NONE,
    )
    entity.settlement_id = None

    # Attempt path traversal via the filename
    snippet = CodeSnippet(
        id=1,
        author_id=1,
        language=CodeLanguage.PYTHON,
        content="print('hi')",
        description="traversal test",
        quality=0.5,
        tick_created=0,
        lines=1,
        filename="../../../escape.py",
    )

    cg._save_code_to_file(StubWorld(), snippet, entity)

    # File should end up inside the output dir (sanitised), not outside
    output_root = (tmp_path / "output").resolve()
    # Walk output dir — all written files must be inside
    for root, _dirs, files in os.walk(output_root):
        for f in files:
            full = (pathlib_resolve(root) / f)
            assert str(full).startswith(str(output_root))


def pathlib_resolve(p):
    import pathlib
    return pathlib.Path(p).resolve()


def test_save_code_writes_file_in_output_dir(tmp_path, monkeypatch):
    import systems.code_gen as cg
    from core.enums import CodeLanguage, EntityType, Gender, Role
    from core.models import CodeSnippet, Entity

    monkeypatch.setattr(cg, "CODE_OUTPUT_DIR", str(tmp_path / "output"))

    class StubWorld:
        settlements: dict = {}

    entity = Entity(
        id=42, x=0.0, y=0.0, entity_type=EntityType.DEVELOPER,
        energy=0.8, gender=Gender.FRONTEND_SPEC, role=Role.NONE,
    )
    entity.settlement_id = None

    snippet = CodeSnippet(
        id=7, author_id=42, language=CodeLanguage.PYTHON,
        content="def foo():\n    return 1\n",
        description="utility", quality=0.8, tick_created=1, lines=2,
        filename="utility.py",
    )
    cg._save_code_to_file(StubWorld(), snippet, entity)

    output_root = tmp_path / "output"
    assert output_root.exists()
    files = list(output_root.rglob("*.py"))
    assert files, "expected at least one generated .py file"
    written = files[0].read_text(encoding="utf-8")
    assert "def foo()" in written
    assert "# Generated by Developer #42" in written
