"""Soul — persistent persona + long-term memory for special entities.

A Soul is what makes an Entity "someone". It survives across ticks, across
save/load cycles, and even across death (reincarnation). It carries:

  - A persona (stable character: traits, preferences, beliefs)
  - Long-term memory (significant events, compressed over time)
  - An identity (name, birth tick, generation lineage)
  - Optional external binding (OpenClaw persona file, if that integration
    is enabled)

Not every Entity has a Soul. Souls are granted selectively (team leaders,
architects, elders, AI copilots). This keeps the "named characters" list
small and meaningful.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import Optional


# ================== Soul Memory ==================

@dataclass
class SoulMemory:
    """A single long-term memory entry.

    kind:
      - "birth"       — soul was granted
      - "achievement" — significant event (led team, discovered tech, etc.)
      - "loss"        — lost something (war, bug, companion)
      - "relation"    — formed a bond with another soul
      - "reflection"  — compressed summary of a period
      - "external"    — event originated from outside the sim (e.g. admin chat)
    """
    tick: int
    kind: str
    text: str
    weight: float = 1.0           # importance 0..1 (used for compression)
    other_soul_id: Optional[str] = None
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "tick": self.tick,
            "kind": self.kind,
            "text": self.text,
            "weight": self.weight,
            "other_soul_id": self.other_soul_id,
            "metadata": self.metadata,
        }

    @staticmethod
    def from_dict(d: dict) -> "SoulMemory":
        return SoulMemory(
            tick=d["tick"],
            kind=d["kind"],
            text=d["text"],
            weight=d.get("weight", 1.0),
            other_soul_id=d.get("other_soul_id"),
            metadata=d.get("metadata", {}),
        )


# ================== Soul ==================

@dataclass
class Soul:
    """A persistent persona bound to an entity.

    `entity_id` is the *current* body. When the entity dies, a Soul may be
    reincarnated into a new body (entity_id is updated, `rebirth_count`
    increases, and a "death+rebirth" memory is appended).
    """
    id: str                           # stable UUID, survives death
    entity_id: int                    # current body
    name: str
    role: str                         # "Team Lead", "Architect", "Elder", ...
    born_tick: int
    personality_summary: str          # one-paragraph stable description

    # Stable traits snapshot (from entity at birth of soul — serves as
    # "core identity" even if entity body drifts)
    traits: dict = field(default_factory=dict)

    # Long-term memory stream
    memory: list[SoulMemory] = field(default_factory=list)

    # Derived, periodically regenerated by LLM:
    reflection: str = ""              # compressed summary of life so far (what happened)
    reflection_tick: int = 0

    # Stable identity layer (DeepTutor dual-memory pattern):
    # `reflection` answers "what happened"; `profile` answers "who am I".
    profile: str = ""                 # stable self-description: values, style, goals
    profile_tick: int = 0

    # Learned capabilities (Hermes skill loop): each entry is
    # {"name": str, "description": str, "acquired_tick": int, "uses": int}.
    skills: list[dict] = field(default_factory=list)

    # Lineage
    rebirth_count: int = 0
    previous_entity_ids: list[int] = field(default_factory=list)
    parent_soul_id: Optional[str] = None   # inherited from a parent soul

    # External integration
    openclaw_bound: bool = False      # if True, this soul is mirrored in Claw

    # Runtime bookkeeping
    last_active_tick: int = 0
    dialogue_partners: dict = field(default_factory=dict)  # soul_id -> affinity

    def remember(
        self,
        tick: int,
        kind: str,
        text: str,
        weight: float = 1.0,
        other_soul_id: Optional[str] = None,
        **meta,
    ) -> None:
        self.memory.append(SoulMemory(
            tick=tick, kind=kind, text=text, weight=weight,
            other_soul_id=other_soul_id, metadata=meta or {},
        ))
        self.last_active_tick = tick

    def recent_memories(self, n: int = 8) -> list[SoulMemory]:
        return self.memory[-n:] if self.memory else []

    def important_memories(self, n: int = 5) -> list[SoulMemory]:
        return sorted(self.memory, key=lambda m: m.weight, reverse=True)[:n]

    def update_affinity(self, other_soul_id: str, delta: float) -> None:
        cur = self.dialogue_partners.get(other_soul_id, 0.0)
        self.dialogue_partners[other_soul_id] = max(-1.0, min(1.0, cur + delta))

    def affinity(self, other_soul_id: str) -> float:
        return self.dialogue_partners.get(other_soul_id, 0.0)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "entity_id": self.entity_id,
            "name": self.name,
            "role": self.role,
            "born_tick": self.born_tick,
            "personality_summary": self.personality_summary,
            "traits": self.traits,
            "memory": [m.to_dict() for m in self.memory],
            "reflection": self.reflection,
            "reflection_tick": self.reflection_tick,
            "profile": self.profile,
            "profile_tick": self.profile_tick,
            "skills": list(self.skills),
            "rebirth_count": self.rebirth_count,
            "previous_entity_ids": self.previous_entity_ids,
            "parent_soul_id": self.parent_soul_id,
            "openclaw_bound": self.openclaw_bound,
            "last_active_tick": self.last_active_tick,
            "dialogue_partners": self.dialogue_partners,
        }

    @staticmethod
    def from_dict(d: dict) -> "Soul":
        s = Soul(
            id=d["id"],
            entity_id=d["entity_id"],
            name=d["name"],
            role=d["role"],
            born_tick=d["born_tick"],
            personality_summary=d.get("personality_summary", ""),
            traits=d.get("traits", {}),
            reflection=d.get("reflection", ""),
            reflection_tick=d.get("reflection_tick", 0),
            profile=d.get("profile", ""),
            profile_tick=d.get("profile_tick", 0),
            skills=list(d.get("skills", [])),
            rebirth_count=d.get("rebirth_count", 0),
            previous_entity_ids=list(d.get("previous_entity_ids", [])),
            parent_soul_id=d.get("parent_soul_id"),
            openclaw_bound=d.get("openclaw_bound", False),
            last_active_tick=d.get("last_active_tick", 0),
            dialogue_partners=dict(d.get("dialogue_partners", {})),
        )
        s.memory = [SoulMemory.from_dict(m) for m in d.get("memory", [])]
        return s


def new_soul_id() -> str:
    return uuid.uuid4().hex[:12]
